services:
  backend:
    build: .
    container_name: portfolio_backend
    ports: 
      - "3333:3000"
    volumes:
      - ./backend:/app
    depends_on: 
      - mongo_container

    #environment:
    #  - PORT=3000
    #  - DB_URL=mongodb://mongo:28017/portfoliodb
    
  mongo_container:
    image: mongo:6
    container_name: portfolio_database
    ports: 
      - "28017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: