services:
  backend:
    build: .
    container_name: portfolio_backend
    ports: 
      - "3333:3000"
    env_file:
      - .env


    #depends_on: 
    #  - mongo_container

    #environment:
    #  - PORT=3000
    #  - DB_URL=mongodb://mongo:28017/portfoliodb
    
  #mongo_container:
  #  image: mongo:6
  #  container_name: portfolio_database
  #  ports: 
  #    - "28017:27017"
